version: '3.9'
services:
  app:
    build: .
    ports:
      - $PORT:$PORT
    environment:
      MONGODB_DATABASE: $MONGODB_DATABASE
      MONGODB_URI: $MONGODB_URI
      MONGODB_MOVIES_COLLECTION: $MONGODB_MOVIES_COLLECTION
      PORT: $PORT
      GIN_MODE: $GIN_MODE
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_USERNAME: $MONGO_INITDB_USERNAME
      MONGO_INITDB_PASSWORD: $MONGO_INITDB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
     