# best practice is to be handle this is vault or external-secrets operator or something similar
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semi-task.fullname" . }}
  labels:
    {{- include "semi-task.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_DATABASE: c2VtaS10YXNr
  MONGODB_URI: bW9uZ29kYjovL2FwcDpkdW1teWFwcEBtb25nby5tb25nbzoyNzAxNw==