# best practice is to be handle this is vault or external-secrets operator or something similar
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZHVtbXk=
  MONGO_INITDB_ROOT_PASSWORD: ZHVtbXlwYXNz
  MONGO_INITDB_USERNAME: YXBw
  MONGO_INITDB_PASSWORD: ZHVtbXlhcHA=
  MONGO_INITDB_DATABASE: c2VtaS10YXNr